sudo: false
language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - gem install jekyll
  - gulp lint
  - gulp css
cache:
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
