sudo: false
language: node_js
node_js:
  - "stable"
install:
  - npm install
  - bower install
script:
  - gulp lint
  - gulp less
cache:
  directories:
    - node_modules
    - bower_components
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
