current_version: 3.3.7

fa_version: 4.6.3
jquery_version: 3.1.0
bootstrap_version: 3.3.7

exclude: [node_modules, bower_components, base16, package.json, bower.json, m8ke, LICENSE, README.md, sourcemaps.js, gulpfile.js]
